version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    working_dir: /app
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./lab1:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db:5432/library_db

volumes:
  pgdata:
