version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
       - ./lab5:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
    environment:
      - MONGODB_URL=mongodb://mongo_admin:password@mongo_db:27017/books?authSource=admin


volumes:
  mongo_data:
